### ISSUE TITLE
How exactly do I use convertObject?

### ISSUE THREAD

**Issue by niculistana** [Mermade/swagger2openapi#40]
### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain

### Detailed Description

I have tried the following:

```
const converter = require('swagger2openapi');
let api = {
          swagger: "2.0"
}
```

```
converter.convertObj(JSON.stringify(api), opts, function (err, options) {
    console.log(options);
    console.log(err);
});
```

The following is returned:

```
undefined
Error: Unsupported swagger/OpenAPI version: undefined
    at /Users/nicu.listana/Work/open-api-transform/open-api-transform-js/node_modules/swagger2openapi/index.js:1158:27
    at new Promise (<anonymous>)
    at Object.convertObj (/Users/nicu.listana/Work/open-api-transform/open-api-transform-js/node_modules/swagger2openapi/index.js:1127:28)
    at Object.<anonymous> (/Users/nicu.listana/Work/open-api-transform/open-api-transform-js/index.js:18:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I am not sure what I pass for the first parameter of the `convertObj` method.

#### Other stuff

widdershins

**Comment by MikeRalphson** [comment]
convertObj expects an object as the first parameter, so you can simply remove the JSON.stringify call.

**Comment by niculistana** [comment]
@MikeRalphson Thanks! Works well, for some reason the json I passed initially did not have the right format 😅
