### ISSUE TITLE
ReferenceError: contentType is not defined

### ISSUE THREAD

**Issue by iakovmarkov** [Mermade/swagger2openapi#56]
When I'm trying to validate (invalid) oAPI 3.0 schema, this exception gets thrown.

### Detailed Description
Log:
```
ReferenceError: contentType is not defined
    at checkResponse (/home/markov/Projects/tapeer-definitions/node_modules/swagger2openapi/validate.js:502:21)
    at checkPathItem (/home/markov/Projects/tapeer-definitions/node_modules/swagger2openapi/validate.js:720:21)
    at validateSync (/home/markov/Projects/tapeer-definitions/node_modules/swagger2openapi/validate.js:1025:13)
    at /home/markov/Projects/tapeer-definitions/node_modules/swagger2openapi/validate.js:1219:9
    at Generator.next (<anonymous>)
    at onFulfilled (/home/markov/Projects/tapeer-definitions/node_modules/co/index.js:65:19)
    at /home/markov/Projects/tapeer-definitions/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/home/markov/Projects/tapeer-definitions/node_modules/co/index.js:50:10)
    at Object.validate (/home/markov/Projects/tapeer-definitions/node_modules/swagger2openapi/validate.js:1214:5)
```

And yea, if you take a look at the source, it really tries to do weird stuff:
```
checkSchema(contentType.schema,{},'schema',openapi,options);
```

Even my IDE complains. Have you thought about adding ESLint & Prettier to the project, to avoid such simple bugs? 

#### Other stuff

I'm running version `2.11.16` from NPM. I've successfully fixed it and will submit PR in a minute.

**Comment by MikeRalphson** [comment]
That whole test was a remnant from an early draft of OAS 3.0. I've removed it now.

We have eslint set up on the project but that issue got lost in the noise.
